Integrate library
tdejong00/kernel_tuner pull request #10
Opened 2024-05-19 12:54 UTC by tdejong00

Deze pull request zorgt er voor dat Kernel Tuner gebruikt maakt van onze cache module. Hiervoor waren een paar aanpassingen aan de JSON schema nodig:
1. `verification_time` en `strategy_time` hadden onterecht het type `integer` i.p.v. `number`.
2. `problem_size` stond nu gedefineerd als een `array`, maar dit kan ook een enkele `integer` zijn of een `string`.
Ook heb ik een omschrijving toegevoegd aan de JSON schema.

2024-05-20 13:00 UTC, warnio requested changes
Library ziet er net uit. Je kan nog een patch version bump doen in de schema, mocht dat handig zijn.

Wat ik nog belangrijk vind is dat de type checking in `Cache.Lines.append` aangepast wordt zodat ook floats voor strategy time en verification time aangenomen worden. Als je wil kijken of iets een instantie is meerdere types is, kun je een tupel meegeven aan `isinstance()`

2024-05-20 13:00 UTC, warnio commented on kernel_tuner/schema/cache/1.0.0/schema.json
Het leek mij nog verstandig om hier een patch version bump te doen. 

Nu verification time en strategy time gewoon numbers kunnen zijn, kun je ook de type checking in de `Cache.Lines.append` method veranderen?

2024-05-20 13:00 UTC, warnio commented on kernel_tuner/util.py
Integratie ziet er net uit!

2024-05-20 20:49 UTC, TobiasHofstra approved these changes
Ziet er heel goed uit, ik heb geen opmerkingen.

2024-05-20 20:49 UTC, TobiasHofstra commented on kernel_tuner/util.py
Mee eens, goed werk!

2024-05-21 13:04 UTC, rmgerritse approved these changes
Ziet er netjes uit, geen opmerkingen ook!

2024-05-30 14:54 UTC, warnio requested changes
Version constante aanpassen in [kernel_tuner/schema/cache/1.0.1/schema.json](https://github.com/tdejong00/kernel_tuner/pull/10/files#diff-d758b0159eaf0f2f2459cce33d2816a4acdd00f044847c1fea8853f41daa756b) naar 1.0.0, en dan is het klaar

2024-05-30 14:54 UTC, warnio commented on kernel_tuner/schema/cache/1.0.1/schema.json
> +      "const": "1.0.0"
Dit veranderen naar 1.0.1

2024-05-30 17:23 UTC, tdejong00 commented on kernel_tuner/schema/cache/1.0.1/schema.json
> +      "const": "1.0.0"
Aangepast. Schema 1.1.0 had nog niet de aanpassingen van 1.0.1, die heb ik toegevoegd. Daarnaast klopte schema 1.0.0 niet meer met wat het voorheen was (problem_size was niet meer required), dat heb ik ook aangepast.

2024-05-30 23:59 UTC, warnio approved these changes

2024-05-31 19:21 UTC, merged