Cli
tdejong00/kernel_tuner pull request #11
Opened 2024-06-02 13:44 UTC by TobiasHofstra

Deze pull request zorgt ervoor dat de CLI geïmplementeerd wordt. Zie ``kernel_tuner/scripts/cli.py`` voor gebruik.

2024-06-02 15:47 UTC, warnio requested changes
Wat mij opvalt is een boel (dubbele) documentatie. Probeer de focus te leggen op het testen, dan het schrijven van code, en dan het documenteren. 

Ook zitten er nogal blunders in zoals het gebruik van packaging.version voor version parsing, wat niet per se compatibel is met het Semver format. Dit is essentieel om te veranderen.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +"""This file cli_fct.py contains several functions used to perform several operations on cachefiles.
Referentie naar `cli_fct.py` is niet (meer) valide. Eerder iets van:

This module contains several ...

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +   For these main operations to work, there are also helper functions such as convert_new_schema().
Functionaliteiten hier documenteren is prima, maar ik zou zo min mogelijk referenties naar de werkelijke code erin verwerken, zodat de documentatie zo lang mogelijk up-to-date blijft

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +    convert_new_schema(file_list)
Hier verander je dus alle input files? Ik denk niet dat het verstandig is om input bestanden te veranderen naar de laatste versie. Vermeld het op zijn minst, maar ik vind dit niet echt acceptabel.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +from packaging import version
Hier hoort semver gebruikt te worden. Geen packaging.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +    newest_version = max(version_list, key=version.parse)
`cachefile.version` is een `semver.Version` object. Wat hier gedaan wordt is het volgende: 
1. De version (type `semver.Version`) wordt eerst omgezet naar een string.
2. De hoogste versie wordt gevonden door de strings weer naar type `semver.Version` te converten
3. In `convert_new_schema` word de `cachefile.version` van `semver.Version` omgezet naar een string en dan vergeleken.

Over het zicht gezien wordt hier dat string niet nodig zijn. Versions kunnen al op zichzelf vergelijken worden met `<` en `>`, dus max werkt ziezo op een lijst van objecten van type `semver.Version`

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +def convert_new_schema(file_list: List[PathLike]):
Descriptieve functienamen zijn het beste. Verwerk dus in de functie naam dat:
1. De files zelf mogelijk worden veranderd
2. De versie de kleinste versie is die nodig is voor de conversion

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +    """Converts all non-new versioned files in file_list to the newest."""
newest \<iets\>?

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +            raise KeyError(f"Merge error; files '{file_list[0]}' and '{file}' do not have the same schema version.")
`KeyError` is ervoor gemaakt wanneer een key niet in een dict gevonden wordt of een dergelijke structuur. Gebruik van `KeyError` in deze context is dus ongepast. Een zelfgemaakte exception class is dus beter

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +            if resulting_output.lines.get(line) is not None:
Gepaster: `if line in resulting_output.lines:`

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +    """Tries to remove entry `delete_key` from file `infile`, then write to `outfile` by using the `cache.py` functions.
Parameter `delete_key` heeft een naam die impliceert dat het een functie is, aangezien het begint met een werkwoord, namelijk delete. Naam `key` is in dit geval genoeg, maar je zou het ook `key_to_delete` kunnen noemen

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +def delete_line(infile: PathLike,  delete_key: any, outfile=None):
Ik zou de `outfile` hier wel een required argument laten (dus geen default argument meegeven). De cli neemt wellicht de outfile gelijk aan de infile in het geval dat alleen maar een argument wordt gegeven, maar de functies in dit bestand staan in principe los van de CLI, in de zin van dat ze door een willekeurige Python script aangeroepen kunnen worden, wat ook de reden is dat ze buiten de scripts folder staat.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +def get_line(infile: PathLike, key: any):
Key is een `str` en geen `any`. De variable `any` is overigens een functie die kijkt of er in een iterable minstens een truthy value voorkomt, en wordt praktisch nooit gebruikt als type hint (en is daarnaast ook nutteloos als type hint). Als je al een "any" wil gebruiken dan heb je `typing.Any` nodig.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +    print(dict(cache_line.items()))
`.items()` kan hier volgens mij weggelaten worden.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +    if cache_infile.version != LATEST_VERSION:
Ik heb eigenlijk het liefst dat Cache alleen overstag kan gaan met de laatste cache version, wat betekent dat die dan zal checken of het de `LATEST_VERSION` heeft. Wat denken jullie?

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +def delete_line(infile: PathLike,  delete_key: any, outfile=None):
Misschien is het ook nog een handig idee om meerdere keys in keen keer van een bestand te kunnen deleten.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +def delete_line(infile: PathLike,  delete_key: any, outfile=None):
Wat als outfile dezelfde waarde heeft als infile en de interne state van `Cache` afhangt van de inhoud van het bestand op het moment? Dan kun je `cache_infile` niet tegelijkertijd gebruiken met `cache_outfile`.

Oplossingen:
1. In het geval dat de infile hetzelfde is als de outfile, zou je het kunnen verplaatsen naar een tijdelijke directory, zodat het bestand waaruit je leest niet het bestand is waar je naar schrijft.
2. Je kan de inhoud van lines verplaatsen naar een dict en ze daaruit overkopieren

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +        raise ValueError("Please specify a .json file for the output file")
Vermeld expliciet dat je een .json extension in de file name verwacht. In principe, hoort deze functionaliteit in de `cli.py`.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +        raise ValueError("Please specify a .json file for the output file")
Verplaats deze checks naar `cli.py`
En als je deze checks hier doet, kun je ze beter ook in `delete_line` en `get_line` doen

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/cli_functionality.py
> +def get_line(infile: PathLike, key: any):
Als je extra checks (om te kijken of de file bestaat) in de andere functies doet, waarom zijn ze hier niet toegevoegd? Los van dat horen die checks eerder in cli.py.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +					help=f"The cachefiles to merge (minimum two). They must be of the same version, and "
Er wordt niet bij vermeld dat in het geval dat ze niet dezelfde versie hebben dat ze dan veranderd worden. Ik adviseer om de automatische version conversion van de bestanden weg te halen.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +					help=f"The cachefiles to merge (minimum two). They must be of the same version, and "
Als alternatief zou een van de volgende dingen kunnen doen:
1. Converteer het json object op zichzelf
2. Kopieer de bestanden naar een aparte directory en convert ze daar

2024-06-02 15:47 UTC, warnio commented on new
Ik zie dat er een file zonder extension is toegevoegd. Het lijkt mij handig dat alle files een extension hebben. Daarnaast is het ook nog niet duidelijk alleen uit de naam gezien wat diens functie is.

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/convert.py
> +        ``target`` is the version that the cache should be converted to. By
Wordt hier `target_version bedoeld`?

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/convert.py
> +        target_version = versions[-1]
Het is niet zeker of dit ook daadwerkelijk de laatste versie is

2024-06-02 15:47 UTC, warnio commented on kernel_tuner/cache/convert.py
> +        versions = list(map(str, VERSIONS))
Voorkeur voor hierbij om de `semver.Version` objecten te gebruiken.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +"""
Deze documentatie is dubbelop. Er zijn zo dan drie plaatsen waar de documentatie bijgehouden moet worden, namelijk in `cli_functionality.py`, `cli.py`, en het commando `cli --help`.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +$ cli t4 --in unconverted.json --out converted.json
Commando heet `ktcache`, niet `cli`. Deze example usages kun je ook toevoegen in help. Je kan de naam van het programma verkrijgen met `argv[0]`

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +$ poetry run ktcache {convert, t4, delete-line, get-line, merge}
Poetry is niet per se nodig. Nog oude niet up-to-date documentatie dus

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +$ poetry run ktcache {convert, t4, delete-line, get-line, merge}
Is al getest of alles werkt via pip?

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +
Hieronder kun je alle checks doen, of bestanden wel bestaan en de juiste naam hebben. Je zou daarvoor ook nog extra functies kunnen schrijven.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +    """The main function for handling conversion to a `schema_version` in the cli. Calls `convert` to convert."""
```Calls `convert` to convert.```. Interne werking hoeft niet tot deze mate gedocumenteerd te worden. Slechts wellicht dat een interne functie wordt aangeroepen en dat deze functie bedoeld is om geparsde argumenten te valideren en door te geven, maar ik zou zelfs over dat twijfelen of ik het erin zou zetten

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +    """The main function for handling deletion of a cacheline using `delete-line` in the cli. Calls `delete_line`."""
Zelfde hier en in de onderstaande functies als in de comment die ik het laatst bij de vorige functie heb gegeven.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +def cli_deleteline(ap_res: argparse.Namespace):
`cli_delete_line`

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +		epilog="More help/issues? Visit https://github.com/kernel_tuner/kernel_tuner")
Hier zal je wellicht een deel van de module documentatie kwijt kunnen.

2024-06-02 15:47 UTC, warnio commented on scripts/cli.py
> +    This is one of {convert, delete-line, get-line, merge},
`t4` format vergeten te documenteren.

2024-06-02 15:47 UTC, warnio commented on test/test_cli.py
> +        parser.func(parser)
Test je ook de output in `stdout`?

2024-06-02 15:47 UTC, warnio commented on test/test_cli.py
> +    def test_merge_correct_two(self, tmp_path):
Grammatisch valide zinnen graag gebruiken. `test_verge_two_correct_caches`

2024-06-02 15:47 UTC, warnio commented on test/test_cli.py
> +    def test_merge_overlapping_keys(self, tmp_path):
`test_merge_when_keys_overlap`

2024-06-02 16:39 UTC, tdejong00 approved these changes
Ik heb naast de uitgebreide review van @warnio niet echt iets toe te voegen. De paar puntjes die ik had zijn al in zijn review benoemd. Als de puntjes van die review zijn opgelost, kan het dus wat mij betreft gemerged worden.

2024-06-04 11:46 UTC, warnio approved these changes

2024-06-04 11:56 UTC, warnio approved these changes

2024-06-10 10:35 UTC, merged