Convertcache
tdejong00/kernel_tuner pull request #3
Opened 2024-03-13 15:39 UTC by TobiasHofstra

2024-03-20 19:39 UTC, tdejong00 requested changes
Code looks fine to me!

Because all the features we will implement have something to do with cache files, I think they should all use the same top-level directory (the _cache_ directory). So I think we should move the `convert.py` to that directory (possibly a sub-directory inside that directory). The _convert_ directory now also has the file `old_cache.json`, this seems like a mistake, as it is also present in the _test_ directory.

Also, what exactly is the intention of the _convert_temp_ directory? Shouldn´t the `convert.py` use the _../schema/cache_ directory, where the actual schemas are located? These files are used by the tests, so I think we should move them to the _test_ directory. But maybe I am misunderstanding.

2024-03-20 19:39 UTC, tdejong00 commented on kernel_tuner/convert/convert.py
> +def convert_cache_file(filestr):
Missing docstring (required by our DoD), same for `default_convert`

2024-03-20 22:47 UTC, warnio requested changes
De code lijkt te doen wat het hoort te doen. Ik geef als feedback de volgende opmerkingen en aanbevelingen.
1. **Ik raad aan om geen test/mock bestanden op te slaan in `kernel_tuner/schema`.**

   Test bestanden zijn op het moment opgeslagen in de `schema` directory van de Kernel Tuner. Het is wellicht handig als je zelf een lijst van conversion functies mee kan geven of een pad naar de test schemas
2. **Ik raad aan niet gebruik te maken van de `globals` functie.** 

   Aangezien je je in dit geval zal beperken tot versions die om te zetten zijn tot Python identifiers. Semver versions kunnen bijvoorbeeld ook dashes bevatten en andere tekens bijvoorbeeld `1.2.3-beta`, en dan werkt de code niet meer. Het is dus handiger om de conversion functies in een dict op te slaan.
3. **Aan mij is de rol van `default_convert` onduidelijk.** 

   Ik ga ervan uit dat de ontwikkelaars bij elke nieuwe versie van de cache een nieuwe conversion functie schrijven, dus het lijkt mij niet dat er een `default_convert` nodig is. Het kan echter zo zijn dat een cache zonder version omgezet moet worden naar een met een version. Dan vermeldt de naam van de functie dit uiteraard

Mocht je de ideeën in deze review willen verwerken, dan heb ik [hier](https://gist.github.com/warnio/5202ca6f1d63877dbacea77d88436c39) een template voor je. De code voldoet zoals Tim zei nog niet aan DoD, dus geen tijd voor approval.

2024-03-20 22:47 UTC, warnio commented on kernel_tuner/convert/convert.py
> +    versions = list(map (lambda v:v.name, sorted(SCHEMA_VERSIONS_PATH.iterdir())))
Maak een global variabel van `versions`

2024-03-20 22:47 UTC, warnio commented on kernel_tuner/convert/convert.py
> +    func_list = globals()
Net zoals je een global maakt van versions kun je ook een global maken van de functions. Ik heb een voorkeur voor het volgende, aangezien er dan geen arbitrary code/function execution is. Denk aan iets als:

```python
CONVERSION_FUNCTIONS = {
    ("1.0.0", "1.0.1"): c_1_0_0_to_1_0_0,
    ("1.0.1", "1.0.2"): c_1_0_1_to_1_0_2,
    ("1.0.2", "1.1.0"): c_1_0_2_to_1_1_0,
}
```

2024-03-20 22:47 UTC, warnio commented on kernel_tuner/convert/convert.py
> +    print("Cache file '{}' converted from version {} to version {}".format(filestr, orig_version, version))
Als deze functie vanuit python wordt aangeroepen, dan wordt ook geprint. Ik kan het mij voorstellen dat wanneer je de converter van de command line aanroept zo'n print statement handig is. Is het ook de bedoeling dat altijd dit wordt geprint?

2024-03-20 22:47 UTC, warnio commented on kernel_tuner/convert/convert.py
> +def default_convert(cache, oldver, newver):
Ik neem aan dat we voor elke versie een conversion functie zullen maken. Wat is in dat geval de rol van default convert?

2024-03-20 22:47 UTC, warnio commented on kernel_tuner/convert/convert.py
> +    func_list = globals()
Bijkomend voordeel is dat je zo'n dictionary mee kunt geven tijdens het testen als een parameter, zeg `conversion_functions` zodat je geen test bestanden in `kernel_tuner/schema/cache/` hoeft te zetten. Je kan deze parameter een default waarde van `None` geven. Wanneer het programma detecteert dat de waarde `None` is zet het `conversion_functions` gelijk aan de global `CONVERSION_FUNCTIONS`

2024-03-20 22:47 UTC, warnio commented on test/test_convert_cache.py
> +    def test_convert(self):
Gebruik een [`tmp_path` fixture](https://docs.pytest.org/en/6.2.x/tmpdir.html), zodat er geen bestanden worden gewijzigd binnen dit project

2024-03-20 22:47 UTC, warnio commented on kernel_tuner/convert/convert.py
> +def convert_cache_file(filestr):
Ik zou deze functie splitten in een functie die een cache _file_ omzet en een functie die een cache _object_ (JSON) omzet

2024-03-21 16:08 UTC, TobiasHofstra commented
Dankje voor de reviews. Voordat ik aanpassingen maak wil ik het nog hebben over het testen van de cache conversion. Namelijk, het idee in het uiteindelijke project is dat voor het testen je een cache file van oudste version probeert te converten naar de nieuwste. 

Nu hebben we echter alleen 1 versie, dus om convert.py te testen had ik een kleine voorbeeld directory gemaakt. Het probleem is dan dat die directory niet naar de main branch moet, maar zonder die directory ik niet kan testen. Ik wil dan ook geen systeem schrijven die dan aparte schema files en conversion functies gebruikt om te testen, want zodra de tweede cache file version gereleased wordt heeft dat geen zin meer (bovendien is het testen op aparte files geen garantie dat de "echte" files goed geconvert worden).

Wat denken jullie?



Nog een ding over de "default convert": het idee was dat veel nieuwe cache file versions kleine verschillen hebben (bijvoorbeeld maar een veld extra), en dat dan geen nieuwe conversion function geschreven hoeft te worden.

2024-03-23 14:12 UTC, warnio commented
> Nu hebben we echter alleen 1 versie, dus om convert.py te testen had ik een kleine voorbeeld directory gemaakt. Het probleem is dan dat die directory niet naar de main branch moet, maar zonder die directory ik niet kan testen. Ik wil dan ook geen systeem schrijven die dan aparte schema files en conversion functies gebruikt om te testen, want zodra de tweede cache file version gereleased wordt heeft dat geen zin meer (bovendien is het testen op aparte files geen garantie dat de "echte" files goed geconvert worden).
>
> Wat denken jullie?

Je hoeft niet per se te testen op echte cache files. Ik zou een mock maken om te kijken of het systeem goed werkt.

> Nog een ding over de "default convert": het idee was dat veel nieuwe cache file versions kleine verschillen hebben (bijvoorbeeld maar een veld extra), en dat dan geen nieuwe conversion function geschreven hoeft te worden.

Het kan een handige functie zijn. Ik zie nog geen concrete cases waar men het op dit moment zou gebruiken, dus ik zou het nog niet toevoegen. Het is een feature op zich en is daarnaast ook geen eis voor de backlog item.

2024-03-23 14:37 UTC, TobiasHofstra commented
> Je hoeft niet per se te testen op echte cache files. Ik zou een mock maken om te kijken of het systeem goed werkt.

Dat klinkt goed. Dat werkt dan denk ik ook gelijk beter voor het testen. Dan kan ik eerst met de mock schemas het systeem testen, en dan met de "echte" schema's de geïmplementeerde conversion functies testen. Dankjewel.

> Het kan een handige functie zijn. Ik zie nog geen concrete cases waar men het op dit moment zou gebruiken, dus ik zou het nog niet toevoegen. Het is een feature op zich en is daarnaast ook geen eis voor de backlog item.

Als ik het goed herinner had ik deze feature al besproken in de vorige klant meeting, en vond Ben het een goed idee. Ik wil het dus wel toevoegen, maar misschien kunnen we het wel nog een keer met de klant bespreken. 


Ik denk dat het nu voor mij duidelijk is wat ik nog moet doen. Is het misschien handig als ik deze PR close en een nieuwe aanmaak wanneer ik klaar ben? Volgensmij zijn er nu te veel veranderingen om alles in the Github editor te doen. Of kan je bv. een nieuwe commit aan een bestaande PR toevoegen? (ik weet eerlijk gezegd niet heel goed hoe dit allemaal werkt)

2024-03-23 14:42 UTC, tdejong00 commented
> Ik denk dat het nu voor mij duidelijk is wat ik nog moet doen. Is het misschien handig als ik deze PR close en een nieuwe aanmaak wanneer ik klaar ben? Volgensmij zijn er nu te veel veranderingen om alles in the Github editor te doen. Of kan je bv. een nieuwe commit aan een bestaande PR toevoegen? (ik weet eerlijk gezegd niet heel goed hoe dit allemaal werkt)

Je kan inderdaad gewoon meer commits toevoegen aan jouw branch, dan kunnen wij het later opnieuw reviewen.

2024-03-24 17:41 UTC, TobiasHofstra commented
Ik heb zojuist een nieuwe commit gepushed. Hierin heb ik:

De `convert_cache_file` functie herschreven om gebruik te kunnen maken van andere versions en conversion functions.
Het gebruik van `globals` heb vervangen met een `dict` van versions naar conversion functions en een `list` van versions (hier zijn de "versions" gewoon strings).
Het testen van cache file conversion herschreven zodat het gebruik maakt van de `tmp_path` fixture, en apart test met "mock" schema" en "echte" schemas.
docstrings toegevoegd aan `convert_cache_file` en `default_convert`
De `convert.py` file verschoven naar de `cache` directory, en de `convert` directory verwijderd.
Kleine bugfix toegepast in `default_convert`.
Nog een paar kleine aanpassingen gemaakt.

Ik heb dus niet de `convert_cache_file` opgesplitst (way Dylan suggereerde), ik kan op dit moment geen usecase vinden waarvoor je slechts een cache als `dict` object zou willen converten i.p.v. een file zelf converten. Misschien is het wel handig als we een CLI implementeren, maar dat zien we dan wel.

Merk ook op dat ik in deze commit `semver` heb toegevoegd aan de project dependencies in de `project.toml` file. Gezien dit project was dat vroeger of later wel nodig denk ik.

2024-03-25 18:40 UTC, warnio requested changes
Wanneer je tests voor de errors hebt toegevoegd, zal ik het goed vinden om te mergen. De opmerkingen die gemaakt zijn kun je nog verwerken. Het lijkt mij ook handig om ze op te nemen in de DoD:

1. De major versies van de package dependencies staan vast
2. De versies van de cache files worden behandeld en vergeleken zoals semver het specificeert
3. De `raises` statements in de functies worden getest in de unit tests

Er zit o.a. een wildcard version in de `pyproject.toml` voor semver. Nu kan elke versie van server gebruikt worden. Zie comment voor meer info.

Daarnaast mag het sorteren van versies gedaan worden zoals gespecificeerd door semver. We hebben het niet in de eisen staan, dus dit toevoegen is optioneel. Voor `default_convert` is het handig om nog te documenteren dat de versions gesorteerd moeten zijn, of er rekening mee te houden dat ze niet gesorteerd zijn.

2024-03-25 18:40 UTC, warnio commented on kernel_tuner/cache/convert.py
> +VERSIONS = list(map (lambda v:v.name, sorted(SCHEMA_VERSIONS_PATH.iterdir())))
Door aan sorted een key functie mee te geven, kun je de versions omzetten naar objecten die een op een [met elkaar vergeleken](https://python-semver.readthedocs.io/en/latest/usage/get-min-and-max-of-multiple-versions.html#sec-max-min) kunnen worden. Ik zou daarnaast eerst mappen, en daarna sorteren, dus

```python
list(sorted((p.name for p in SCHEMA_VERSIONS_PATH.iterdir()), key=semver.Version.parse))
```

Semver `Version` objecten kunnen namelijk met elkaar vergeleken worden door middel van bijvoorbeeld `<` en `>` operaties. Op die manier vergelijk je daadwerkelijke versie objecten en is komt `1.0.0-alpha` bijvoorbeeld voor `1.0.0` i.p.v. na, zoals voorgeschreven door de semver specificatie

Een beschrijvende naam zoals `SORTED_VERSIONS` kan daarnaast handiger zijn

2024-03-25 18:40 UTC, warnio commented on kernel_tuner/cache/convert.py
> +    newver = versions[versions.index(oldver) + 1]
Dit gaat ervan uit dat `versions` gesorteerd wordt. Graag erbij documenteren en verwerken in `convert_cache_file`. Daarnaast kun je het beter de naam `sorted_versions` geven, wat je documentatie zal schelen, aangezien de variabel dan al genoeg over zijn inhoud zegt.

In plaats van het bovenstaande kun je ook met server de kleinste grotere versie pakken. Dat zal wat extra regels code vereisen

2024-03-25 18:40 UTC, warnio commented on pyproject.toml
> +semver = "*"
Versie nummer erbij meegeven is wel handig `^3.0.3` geeft aan dat alle versies van 3.0.3 tot onder 4.0.0 gebruikt kunnen worden. Op deze manier voldoet semver 1.0.0 en 0.0.1 er ook aan, ik denk dat hierdoor bepaalde features mogelijk niet werken, waardoor je andere code hebt geschreven dan dat ik had verwacht.

2024-03-25 18:40 UTC, warnio commented on kernel_tuner/cache/convert.py
> +    if semver.VersionInfo.parse(version).compare(target_version) > 0:
`semver.compare(version, target_version)` zal ook al voldoen, maar het kan zo zijn dat je een random versie van de `semver` Python package hebt geïnstalleerd omdat je geen versie hebt gespecificeerd in je pyproject.toml, waardoor je code het niet doet

2024-03-25 18:40 UTC, warnio commented on kernel_tuner/cache/convert.py
> +#######################################################################
Nice. Mooi stukje uitleg

2024-03-25 18:40 UTC, warnio commented on kernel_tuner/cache/convert.py
> +                         f"existing version")
Worden de errors hierboven werkelijk gegeven? Heb je tests ervoor geschreven? Dat kan je makkelijk doen met

```
with pytest.raises(ValueError):
    ...
```

Je kan ook de error message matchen, mocht je dat willen

2024-03-25 18:40 UTC, warnio commented on test/test_convert_cache.py
> +    def test_convert_mock(self, tmp_path):
Maak de naam van de test method langer zodat er geen comment nodig is. Zelfdocumenterende code is bliss 😁

2024-03-25 20:43 UTC, TobiasHofstra commented on kernel_tuner/cache/convert.py
> +    if semver.VersionInfo.parse(version).compare(target_version) > 0:
Blijkbaar is ``semver.compare`` deprecated ([1](https://python-semver.readthedocs.io/en/latest/api.html#module-semver._deprecated), [2](https://github.com/python-semver/python-semver/issues/258)). Vind ik persoonlijk stom, maar wat kan je doen.

2024-03-26 01:21 UTC, TobiasHofstra commented
Heb zojuist weer wat aanpassingen gemaakt.

Alle ValueError cases in ``convert_cache_file`` hebben nu een aparte test. Ik heb ook test support aan ``default_convert`` toegevoegd en hiervoor een test geschreven. 
semver heeft als project dependency nu een required version van ``^3.0.0``.
Ik heb deze regel:
```python
list(sorted((p.name for p in SCHEMA_VERSIONS_PATH.iterdir()), key=semver.Version.parse))
```
Uit Dylan's feedback direct overgenomen. ``default_convert`` maakt nu ook gebruik van ``semver`` om de volgende hogere versie te bepalen.

Ik heb ook de docstring van de twee functies aangepast om te zeggen dat ``versions`` een gesorteerde lijst moet zijn.

En nog een paar kleine fixes.

2024-03-26 13:59 UTC, tdejong00 approved these changes
Goede verbeteringen, wat mij betreft kan dit gemerged worden

2024-03-26 14:18 UTC, warnio approved these changes

2024-03-26 18:39 UTC, merged