Load and Store cache files
tdejong00/kernel_tuner pull request #5
Opened 2024-03-26 18:14 UTC by rmgerritse

2024-03-27 15:36 UTC, TobiasHofstra requested changes
De code lijkt erg goed en doet wat het moet doen. Ik had nog wel een paar opmerkingen, vooral over consistentie van de structuur van het project.

2024-03-27 15:36 UTC, TobiasHofstra commented on KTLibrary/FormattedEncoder.py
> +        # Overwrites the encode function of the JSONEncoder by a custom one.
Het is waarschijnlijk best om dit commentaar als een docstring met """triple double quotes""" te schrijven i.p.v. met #'s.

2024-03-27 15:36 UTC, TobiasHofstra commented on KTLibrary/README.MD
> +## To Dos:
Deze todo's zijn toch af nu?

2024-03-27 15:36 UTC, TobiasHofstra commented on SampleCacheFiles/convolution_A100.json
Het lijkt me best om deze file (en de andere file in SampleCacheFiles) te verplaatsen naar ``kernel_tuner/test/test_cache_files`` (of een nieuwe directory in de ``test/`` directory).

2024-03-27 15:36 UTC, TobiasHofstra commented on test.py
Deze file moet denk ik weg toch? Aangezien er al tests in ``test/test_cachefile.py`` zitten.

2024-03-27 15:36 UTC, TobiasHofstra commented on test/test_cachefile.py
> +    p = Path.joinpath(Path(os.getcwd()), 'KTLibrary', 'test.json')
In het algemeen kan je geen aannames maken over van waar de test file gerunt wordt, dus maak de paths file-relative met gebruikt van ``__file__``.

2024-03-27 15:36 UTC, TobiasHofstra commented on test/test_cachefile.py
Volgens mij kan deze file een betere naam hebben, er bestaat namelijk een ``test_cache_file`` in de main branch.

2024-03-27 15:36 UTC, TobiasHofstra commented on test/test_cachefile.py
> +def test_write_cache_file():
Gebruik een [`tmp_path` fixture](https://docs.pytest.org/en/6.2.x/tmpdir.html), zodat er geen bestanden worden gewijzigd binnen dit project.

2024-03-28 17:27 UTC, warnio requested changes
Mijn feedback:
1. Zorg ervoor dat er zoveel mogelijk gebruik wordt gemaakt van de directory structuur die al aanwezig is. Zet alles in `KTLibrary` daarom over naar `kernel_tuner/cache`. Het is ook handig om consistent camel case te blijven gebruiken.
2. Catch geen exceptions tenzij het echt nodig is. Het is handiger om in de docstrings te zetten welke exceptions er verwacht kunnen worden. Welke exceptions bepaalde functies kunnen gooien zijn op te zoeken in de Python documentatie.
3. Print niks als het niet per se nodig is. Gebruik Exceptions voor errata
4. Gebruik docstrings (met triple quotes `"""`) voor documentatie

2024-03-28 17:27 UTC, warnio commented on KTLibrary/README.MD
> +## To Dos:
Deze mogen weg inderdaad

2024-03-28 17:27 UTC, warnio commented on SampleCacheFiles/convolution_A100.json
Mee eens

2024-03-28 17:27 UTC, warnio commented on test/test_cachefile.py
Een redelijke naam lijkt mij `test_cachefile_read_write.py`

2024-03-28 17:27 UTC, warnio commented on KTLibrary/FormattedEncoder.py
Verplaatsen naar `kernel_tuner/cache/cache_json_encoder.py`

2024-03-28 17:27 UTC, warnio commented on KTLibrary/FormattedEncoder.py
> +class FormattedEncoder(json.JSONEncoder):
`CacheJSONEncoder` lijkt mij een betere naam

2024-03-28 17:27 UTC, warnio commented on KTLibrary/KTLibrary.py
> +class KTLibrary:
Er is hier nog geen class voor nodig. Voorkeur is voor losse read en write functies die dictionaries als input nemen en als output geven

2024-03-28 17:27 UTC, warnio commented on KTLibrary/KTLibrary.py
> +        except FileNotFoundError as e:
De persoon die de method aanroept hoort de exceptions te handelen

2024-03-28 17:27 UTC, warnio commented on KTLibrary/KTLibrary.py
> +        return json_data
Het is mogelijk dat `json_data` hier niet gedefinieerd is. Verplaats de return binnen de with statement

2024-03-28 17:27 UTC, warnio commented on KTLibrary/KTLibrary.py
> +            print("File not found: ", e)
Daarnaast is het handig om dingen zoals errata te printen. Als je de try weglaat, dan worden errata vanzelf geprint in de shell

2024-03-28 17:27 UTC, warnio commented on KTLibrary/KTLibrary.py
Ook hier weer graag gebruik maken van de bestaande `kernel_tuner/cache` folder. Daarnaast schrijven we niet de kernel tuner library, maar de cache module, wat je wellicht de kernel tuner cache library kan noemen.

2024-04-03 22:45 UTC, TobiasHofstra requested changes
Als ik het goed zie dan staan er nog steeds files in de 'KTLibrary' en 'SampleCacheFiles' directories. Aangezien deze directories in de top-level directory van het Kernel Tuner project staan moet dit echt wel verandered worden vind ik.

De veranderingen die gemaakt zijn zijn goed. Als dus het bovengenoemde probleem is opgelost vind ik het goed om deze PR te approven.

2024-04-04 15:25 UTC, rmgerritse commented on KTLibrary/FormattedEncoder.py
Wij hebben geen cache folder, die heb je aangemaakt in je eigen branch?

2024-04-04 17:08 UTC, rmgerritse commented on KTLibrary/FormattedEncoder.py
heb nu een folder cachefiles aangemaakt en daarin alles ingezet, kernel_tuner/cachefile/

2024-04-04 17:08 UTC, rmgerritse commented on KTLibrary/KTLibrary.py
heb hem in cachefile folder gezet

2024-04-05 19:18 UTC, TobiasHofstra approved these changes
Ik vind het nu goed.

2024-04-06 19:50 UTC, warnio reviewed
Test bestanden het liefst in de `test` folder zetten

2024-04-06 19:50 UTC, warnio commented on kernel_tuner/cache/SampleCacheFiles/convolution_A100.json
Kan deze verplaatst worden naar een subfolder van `test`?

2024-04-07 15:10 UTC, rmgerritse commented on kernel_tuner/cache/SampleCacheFiles/convolution_A100.json
yes

2024-04-07 20:02 UTC, warnio approved these changes

2024-04-08 12:41 UTC, merged