Unversioned convert
tdejong00/kernel_tuner pull request #7
Opened 2024-04-26 12:25 UTC by TobiasHofstra

2024-04-26 15:37 UTC, tdejong00 approved these changes
Ziet goed uit en de tests werken. Misschien handig om te wachten met mergen, aangezien er hoogstwaarschijnlijk dingen moeten worden aangepast aan deze functionaliteit m.b.t. #6 (het inlezen van een cache file bijvoorbeeld)?

2024-04-26 20:57 UTC, warnio commented
Update: #6 is gemerged

2024-05-02 11:54 UTC, rkcash requested changes
De Mock convert functions mogen een @staticmethod erboven zodat het duidelijk is dat ze niet deel zijn van de class.

2024-05-02 11:54 UTC, rkcash commented on test/test_convert_cache.py
>          return
Paar onnodige returns die weg kunnen.

2024-05-12 10:26 UTC, rkcash commented on test/test_convert_cache.py
>          return
staticmethod is toegevoegd nu

2024-05-12 10:27 UTC, rkcash approved these changes

2024-05-12 10:44 UTC, merged